server.port=8888
spring.application.name=vet-gateway

spring.cloud.gateway.routes[0].id=keycloak
spring.cloud.gateway.routes[0].uri=http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/auth/(?<segment>.*), /$\{segment}

# GET localhost:8888/api/appointment/book
# ? localhost:8081/appointment/book (StringPrefix=1)
spring.cloud.gateway.routes[1].id=appointment-service
spring.cloud.gateway.routes[1].uri=http://${APPOINTMENT_HOST:localhost}:${APPOINTMENT_PORT:8081}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/appointment/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[2].id=management-service
spring.cloud.gateway.routes[2].uri=http://${MANAGEMENT_HOST:localhost}:${MANAGEMENT_PORT:8082}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/management/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[3].id=profile-service
spring.cloud.gateway.routes[3].uri=http://${PROFILE_HOST:localhost}:${PROFILE_PORT:8083}
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/profile/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1

# GET localhost:8888/bot/send_message
# ? localhost:8090/send_message (StringPrefix=0)
spring.cloud.gateway.routes[4].id=telegram-bot
spring.cloud.gateway.routes[4].uri=http://${TELEGRAM_HOST:localhost}:${TELEGRAM_PORT:8090}
spring.cloud.gateway.routes[4].predicates[0]=Path=/bot/**
spring.cloud.gateway.routes[4].filters[0]=StripPrefix=0

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.security=DEBUG

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/clinic-realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/clinic-realm}/protocol/openid-connect/certs
#spring.security.oauth2.client.registration.keycloak.client-id=vet-gateway
#spring.security.oauth2.client.registration.keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:oy3FdqCED7Wi4BPX7JZ0Y3ils24UopsR}
#spring.security.oauth2.client.registration.keycloak.authorization-grant-type=client_credentials
#spring.security.oauth2.client.registration.keycloak.provider=keycloak
#spring.security.oauth2.client.provider.keycloak.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/clinic-realm}